version: '3.4'

networks:
    nginx-php74-mysql-rabbitmq:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - mysql8-service
        networks:
            - nginx-php74-mysql-rabbitmq

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - nginx-php74-mysql-rabbitmq

    # mysql
    mysql8-service:
        image: mysql:5.7
        container_name: mysql8-container
        ports:
            - "4306:3306"
            - "43060:33060"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: 123457890
            MYSQL_PASSWORD: 123457890
            MYSQL_DATABASE: news_db
            MYSQL_USER: amo
        networks:
            - nginx-php74-mysql-rabbitmq

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
        - 8081:80
        environment:
            PMA_HOST: mysql8-service
            MYSQL_ROOT_PASSWORD: my_password
        networks:
             - nginx-php74-mysql-rabbitmq
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq-container
        environment:
            RABBITMQ_DEFAULT_USER: rabbitmq_user
            RABBITMQ_DEFAULT_PASS: rabbitmq_password
            RABBITMQ_DEFAULT_VHOST: "/"
            RABBITMQ_URL: "amqp://rabbitmq_user:rabbitmq_password@rabbitmq_host:5672/%2F"
        ports:
            - "15672:15672"
            - "5672:5672"
        networks:
            - nginx-php74-mysql-rabbitmq
        volumes:
            - ./rabbit_config.json:/rabbit_config.json