index:
   path: /
   controller: App\Controller\DashboardController::dashboard
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
delete_news_item:
    path: /news/{id}
    controller: App\Controller\NewsController::delete
    methods: [DELETE,POST]
    requirements:
        id: '\d+'
