old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        news_producer:
            connection: default
            exchange_options:
                name: 'news_exchange'
                type: 'direct'
                durable: true
            queue_options:
                name: 'news_queue'
                durable: true
            default_routing_key: 'news_routing_key'
    consumers:
        news_consumer:
            connection: default
            exchange_options:
                name: 'news_exchange'
                type: 'direct'
                durable: true
            queue_options:
                name: 'news_queue'
                durable: true
            callback: 'App\MessageHandler\NewsConsumer::consume'
            qos_options: { prefetch_count: 1 }
        parallel_news_consumer:
            connection: default
            exchange_options:
                name: 'news_exchange'
                type: 'direct'
                durable: true
            queue_options:
                name: 'news_queue'
                durable: true
            callback: 'App\MessageHandler\ParallelNewsConsumer::consume'
            qos_options: { prefetch_count: 1 }
