old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        news_producer:
            connection: default
            exchange_options: { name: 'news_exchange', type: direct }
    consumers:
        news_consumer:
            connection: default
            exchange_options: { name: 'news_exchange', type: direct }
            queue_options:
                name: 'news_queue'
            callback: 'App\MessageHandler\NewsConsumer::consume'
